name: CI Pipeline Kelompok 5 - Segmentasi Citra

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Download kode
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Langkah 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Langkah 4: Jalankan Linter (Flake8)
      - name: Run Linter (Flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Langkah 5: Jalankan Unit Test
      - name: Run Unit Tests
        run: |
          python -m pytest test_segmentation.py -v

      # Langkah 6: Test run program utama
      - name: Test Run Program
        run: |
          python segmentasi.py
